version: '3.8'
services:
  redis:
    image: redis:6.2-alpine
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning
    volumes:
      - redis-data:/data
  app:
    build: .
    depends_on:
      - redis
    ports:
      - "23567:23567"
    environment:
      - PORT=23567
      - REDIS_URL=redis
volumes:
  redis-data:
    driver: local